import type { ProjectDetection } from './detect-project';

/**
 * Renders a monitor.config.{ts,js} file tailored to the detected
 * project. Returns the file contents as a string; the caller decides
 * where/whether to write it.
 */
export function renderMonitorConfig(detection: ProjectDetection): {
  fileName: string;
  content: string;
} {
  const ext = detection.isTypeScript ? 'ts' : 'js';
  const fileName = `monitor.config.${ext}`;
  const tsImport = detection.isTypeScript
    ? `import { defineMonitorConfig } from '@erne/monitor';\n\nexport default defineMonitorConfig({`
    : `const { defineMonitorConfig } = require('@erne/monitor');\n\nmodule.exports = defineMonitorConfig({`;

  const stateComment =
    detection.stateManagement.zustand || detection.stateManagement.reduxToolkit
      ? `  // StateCollector can be wired via middleware on your existing stores.\n`
      : '';

  const content = `${tsImport}
  // Auto-generated by \`npx @erne/monitor init\` on ${new Date().toISOString().slice(0, 10)}.
  // Edit freely — defineMonitorConfig validates and applies defaults for
  // any field you leave out.
  collectors: {
    crash: true,
    network: true,
    navigation: true,
    custom: true,
    // Dev-only collectors are disabled automatically in production builds.
    render: 'dev',
    frameDrop: 'dev',
    touchBoundary: 'dev',
    frustration: 'dev',
    a11y: 'dev',
    memory: true,
    startup: true,
    replay: 'dev',
  },
  sampling: { dev: 1.0, prod: 0.1 },
${stateComment}  consent: {
    crashes: true,
    analytics: false,
    replay: false,
  },
  ai: {
    crashExplainer: true,
    autoFix: 'suggest',
    maxFilesPerFix: 5,
  },
  transport: {
    endpoint: null,
    batchInterval: 60_000,
    maxBatchSize: 100,
  },
});
`;

  return { fileName, content };
}
