import { describe, expect, test } from 'vitest';
import { parseProGuardMapping, resolveFrame } from './resolver.js';
import type { SymbolFileRecord } from '../storage/types.js';

const SAMPLE_MAPPING = `
# generated by R8
com.example.app.MainActivity -> a.b.c:
    int counter -> d
    12:15:void onCreate(android.os.Bundle) -> e
    void buggyMethod() -> f
com.example.app.Utils -> a.b.d:
    java.lang.String formatDate(long) -> a
`;

function makeProGuardRecord(partial: Partial<SymbolFileRecord> = {}): SymbolFileRecord {
  return {
    id: partial.id ?? 'sym-1',
    platform: 'android',
    bundleId: partial.bundleId ?? 'com.example.app',
    version: partial.version ?? '1.0.0',
    filename: partial.filename ?? 'mapping.txt',
    sizeBytes: partial.sizeBytes ?? 1024,
    uploadedAt: partial.uploadedAt ?? 1_770_000_000_000,
    entryCount: partial.entryCount ?? 0,
    uuid: partial.uuid ?? null,
    mappingText: partial.mappingText ?? SAMPLE_MAPPING,
  };
}

describe('parseProGuardMapping', () => {
  test('parses R8 four-segment line ranges (start:end:origStart:origEnd:)', () => {
    const R8_MAPPING = `com.example.R8Class -> r.s.t:
    12:15:34:50:void onCreate(android.os.Bundle) -> a
    void noRange() -> b
`;
    const mapping = parseProGuardMapping(R8_MAPPING);
    const cls = mapping.classes.get('r.s.t');
    expect(cls?.members.get('a')?.original).toBe('onCreate');
    expect(cls?.members.get('a')?.signature).toBe('(android.os.Bundle)');
    expect(cls?.members.get('b')?.original).toBe('noRange');
  });

  test('indexes classes by obfuscated name and captures member mappings', () => {
    const mapping = parseProGuardMapping(SAMPLE_MAPPING);
    const cls = mapping.classes.get('a.b.c');
    expect(cls?.original).toBe('com.example.app.MainActivity');
    expect(cls?.members.get('e')?.original).toBe('onCreate');
    expect(cls?.members.get('e')?.signature).toBe('(android.os.Bundle)');
    expect(cls?.members.get('f')?.original).toBe('buggyMethod');
    expect(mapping.classes.get('a.b.d')?.original).toBe('com.example.app.Utils');
    // 2 classes + 4 members = 6 indexed entries
    expect(mapping.entryCount).toBe(6);
  });
});

describe('resolveFrame', () => {
  test('deobfuscates class + method given a ProGuard mapping', () => {
    const frame = resolveFrame(
      {
        platform: 'android',
        bundleId: 'com.example.app',
        version: '1.0.0',
        symbol: 'a.b.c.e',
      },
      makeProGuardRecord(),
    );
    expect(frame.resolved).toBe(true);
    expect(frame.symbol).toBe('com.example.app.MainActivity.onCreate(android.os.Bundle)');
    expect(frame.source?.fileId).toBe('sym-1');
  });

  test('falls back to class name when method is unknown, flags no-mapping when artefact missing', () => {
    const classOnly = resolveFrame(
      {
        platform: 'android',
        bundleId: 'com.example.app',
        version: '1.0.0',
        symbol: 'a.b.c.unknownMember',
      },
      makeProGuardRecord(),
    );
    expect(classOnly.resolved).toBe(true);
    expect(classOnly.symbol).toBe('com.example.app.MainActivity');
    expect(classOnly.note).toBe('member-not-found');

    const missing = resolveFrame(
      {
        platform: 'android',
        bundleId: 'com.example.app',
        version: '1.0.0',
        symbol: 'a.b.c.e',
      },
      null,
    );
    expect(missing.resolved).toBe(false);
    expect(missing.note).toBe('no-mapping');
  });

  test('iOS dSYM records are not parsed but return a source pointer', () => {
    const frame = resolveFrame(
      {
        platform: 'ios',
        bundleId: 'com.example.app',
        version: '1.0.0',
        symbol: '0x10004000',
      },
      {
        id: 'sym-ios',
        platform: 'ios',
        bundleId: 'com.example.app',
        version: '1.0.0',
        filename: 'AppDsym.zip',
        sizeBytes: 20_000,
        uploadedAt: 1,
        entryCount: 0,
        uuid: 'ABCDEF01-2345-6789-ABCD-EF0123456789',
        mappingText: null,
      },
    );
    expect(frame.resolved).toBe(false);
    expect(frame.note).toBe('ios-not-parsed');
    expect(frame.source?.fileId).toBe('sym-ios');
  });
});

// Task 117.3 — Hermes / SourceMap v3 path through resolveFrame.
//
// The fixture below is a tiny synthetic v3 map authored at test time —
// no Sentry-CLI files included. Hand-encoding a single segment is the
// simplest "Hermes-shaped" artefact we can author without bringing in
// an external map producer. The full chain test lives in
// hermesMap.test.ts; this test verifies the resolveFrame integration.
describe('resolveFrame — Hermes', () => {
  // mappings: one line, single segment at genCol=0 with all four
  // deltas = 0 plus name index 0. Each `A` decodes to VLQ 0, so the
  // segment is `(0, 0, 0, 0, 0)`: source 0, source line 0, source
  // column 0, name 0. Hand-encoded — no Sentry-CLI files included.
  const HERMES_MAP = JSON.stringify({
    version: 3,
    sources: ['src/Home.tsx'],
    names: ['render'],
    mappings: 'AAAAA',
  });

  function makeHermesRecord(): SymbolFileRecord {
    return {
      id: 'sym-hbc',
      platform: 'ios',
      bundleId: 'com.example.app',
      version: '1.0.0',
      filename: 'index.bundle.map',
      sizeBytes: HERMES_MAP.length,
      uploadedAt: 0,
      entryCount: 0,
      uuid: null,
      mappingText: HERMES_MAP,
    };
  }

  test('resolves bytecode coordinates to original (file, line, column, name)', () => {
    const frame = resolveFrame(
      {
        platform: 'ios',
        bundleId: 'com.example.app',
        version: '1.0.0',
        symbol: 'unknown',
        line: 0,
        column: 0,
      },
      makeHermesRecord(),
    );
    expect(frame.resolved).toBe(true);
    expect(frame.origin).toEqual({
      file: 'src/Home.tsx',
      line: 0,
      column: 0,
      name: 'render',
    });
    // 0-indexed line/column → 1-indexed display.
    expect(frame.symbol).toBe('render (src/Home.tsx:1:1)');
  });

  test('hermes map without coordinates flags hermes-needs-coordinates', () => {
    const frame = resolveFrame(
      {
        platform: 'ios',
        bundleId: 'com.example.app',
        version: '1.0.0',
        symbol: 'unknown',
      },
      makeHermesRecord(),
    );
    expect(frame.resolved).toBe(false);
    expect(frame.note).toBe('hermes-needs-coordinates');
  });

  test('malformed Hermes JSON returns hermes-parse-failed', () => {
    const broken: SymbolFileRecord = {
      ...makeHermesRecord(),
      // Looks Hermes-shaped enough that the sniffer routes here, but
      // the JSON is truncated mid-`mappings` so JSON.parse throws.
      mappingText: '{"version":3,"sources":[],"mappings":"AAA',
    };
    const frame = resolveFrame(
      {
        platform: 'ios',
        bundleId: 'com.example.app',
        version: '1.0.0',
        symbol: 'unknown',
        line: 0,
        column: 0,
      },
      broken,
    );
    expect(frame.resolved).toBe(false);
    expect(frame.note).toMatch(/^hermes-parse-failed:/);
  });
});
