import { describe, expect, test } from 'vitest';
import { parseProGuardMapping, resolveFrame } from './resolver.js';
import type { SymbolFileRecord } from '../storage/types.js';

const SAMPLE_MAPPING = `
# generated by R8
com.example.app.MainActivity -> a.b.c:
    int counter -> d
    12:15:void onCreate(android.os.Bundle) -> e
    void buggyMethod() -> f
com.example.app.Utils -> a.b.d:
    java.lang.String formatDate(long) -> a
`;

function makeProGuardRecord(
  partial: Partial<SymbolFileRecord> = {},
): SymbolFileRecord {
  return {
    id: partial.id ?? 'sym-1',
    platform: 'android',
    bundleId: partial.bundleId ?? 'com.example.app',
    version: partial.version ?? '1.0.0',
    filename: partial.filename ?? 'mapping.txt',
    sizeBytes: partial.sizeBytes ?? 1024,
    uploadedAt: partial.uploadedAt ?? 1_770_000_000_000,
    entryCount: partial.entryCount ?? 0,
    uuid: partial.uuid ?? null,
    mappingText: partial.mappingText ?? SAMPLE_MAPPING,
  };
}

describe('parseProGuardMapping', () => {
  test('indexes classes by obfuscated name and captures member mappings', () => {
    const mapping = parseProGuardMapping(SAMPLE_MAPPING);
    const cls = mapping.classes.get('a.b.c');
    expect(cls?.original).toBe('com.example.app.MainActivity');
    expect(cls?.members.get('e')?.original).toBe('onCreate');
    expect(cls?.members.get('e')?.signature).toBe('(android.os.Bundle)');
    expect(cls?.members.get('f')?.original).toBe('buggyMethod');
    expect(mapping.classes.get('a.b.d')?.original).toBe('com.example.app.Utils');
    // 2 classes + 4 members = 6 indexed entries
    expect(mapping.entryCount).toBe(6);
  });
});

describe('resolveFrame', () => {
  test('deobfuscates class + method given a ProGuard mapping', () => {
    const frame = resolveFrame(
      {
        platform: 'android',
        bundleId: 'com.example.app',
        version: '1.0.0',
        symbol: 'a.b.c.e',
      },
      makeProGuardRecord(),
    );
    expect(frame.resolved).toBe(true);
    expect(frame.symbol).toBe('com.example.app.MainActivity.onCreate(android.os.Bundle)');
    expect(frame.source?.fileId).toBe('sym-1');
  });

  test('falls back to class name when method is unknown, flags no-mapping when artefact missing', () => {
    const classOnly = resolveFrame(
      {
        platform: 'android',
        bundleId: 'com.example.app',
        version: '1.0.0',
        symbol: 'a.b.c.unknownMember',
      },
      makeProGuardRecord(),
    );
    expect(classOnly.resolved).toBe(true);
    expect(classOnly.symbol).toBe('com.example.app.MainActivity');
    expect(classOnly.note).toBe('member-not-found');

    const missing = resolveFrame(
      {
        platform: 'android',
        bundleId: 'com.example.app',
        version: '1.0.0',
        symbol: 'a.b.c.e',
      },
      null,
    );
    expect(missing.resolved).toBe(false);
    expect(missing.note).toBe('no-mapping');
  });

  test('iOS dSYM records are not parsed but return a source pointer', () => {
    const frame = resolveFrame(
      {
        platform: 'ios',
        bundleId: 'com.example.app',
        version: '1.0.0',
        symbol: '0x10004000',
      },
      {
        id: 'sym-ios',
        platform: 'ios',
        bundleId: 'com.example.app',
        version: '1.0.0',
        filename: 'AppDsym.zip',
        sizeBytes: 20_000,
        uploadedAt: 1,
        entryCount: 0,
        uuid: 'ABCDEF01-2345-6789-ABCD-EF0123456789',
        mappingText: null,
      },
    );
    expect(frame.resolved).toBe(false);
    expect(frame.note).toBe('ios-not-parsed');
    expect(frame.source?.fileId).toBe('sym-ios');
  });
});
