// design/tokens/index.ts
import { colors, typography, spacing, springPresets, hapticPairing } from '../hig';

export function generateTokenFile(): string {
  let output = `// Auto-generated by ERNE HIG — do not edit manually\n`;
  output += `// Run: /erne-hig tokens\n\n`;
  output += `import { StyleSheet } from 'react-native';\n\n`;

  // Colors
  output += `export const higColors = {\n  light: {\n`;
  for (const group of [colors.system, colors.labels, colors.backgrounds, colors.fills, colors.separators]) {
    for (const c of group) {
      output += `    ${c.keyword}: '${c.light}',\n`;
    }
  }
  output += `  },\n  dark: {\n`;
  for (const group of [colors.system, colors.labels, colors.backgrounds, colors.fills, colors.separators]) {
    for (const c of group) {
      output += `    ${c.keyword}: '${c.dark}',\n`;
    }
  }
  output += `  },\n} as const;\n\n`;

  // Grays
  output += `export const higGrays = {\n  light: {\n`;
  for (const c of colors.grays) {
    output += `    ${c.keyword}: '${c.light}',\n`;
  }
  output += `  },\n  dark: {\n`;
  for (const c of colors.grays) {
    output += `    ${c.keyword}: '${c.dark}',\n`;
  }
  output += `  },\n} as const;\n\n`;

  // Spacing
  output += `export const higSpacing = {\n`;
  for (const s of spacing.scale) {
    output += `  ${s.keyword}: ${s.value},\n`;
  }
  for (const s of spacing.semantic) {
    output += `  ${s.keyword}: ${s.value},\n`;
  }
  output += `} as const;\n\n`;

  // Typography
  output += `export const higTypography = StyleSheet.create({\n`;
  for (const t of typography.styles) {
    output += `  ${t.keyword}: { fontSize: ${t.size}, fontWeight: '${t.weight}', lineHeight: ${t.lineHeight}, letterSpacing: ${t.tracking} },\n`;
  }
  output += `});\n\n`;

  // Springs
  output += `export const higSprings = ${JSON.stringify(springPresets, null, 2)} as const;\n\n`;

  // Haptics
  output += `export const higHaptics = ${JSON.stringify(hapticPairing, null, 2)} as const;\n\n`;

  // Corner radius scale
  output += `export const higCornerRadius = {\n`;
  output += `  sm: 8,\n  md: 12,\n  lg: 16,\n  xl: 20,\n  xxl: 24,\n  full: 9999,\n`;
  output += `} as const;\n`;

  return output;
}
