// @erne/monitor schema codegen — reads TypeScript event interfaces with
// ts-morph and translates them to Swift structs + Kotlin data classes.
//
// Usage:
//   import { generateSchemas } from './schema-codegen';
//   await generateSchemas({
//     sourceFile: path.join(__dirname, '../../src/types/events.ts'),
//     iosOutDir: path.join(__dirname, '../../ios/generated'),
//     androidOutDir: path.join(__dirname, '../../android/generated'),
//   });
//
// Idempotent: running twice produces identical output (deterministic
// ordering + stable whitespace). Throws if any discovered interface
// contains a type shape the generators cannot translate.

import { Project, ts } from 'ts-morph';
import type {
  InterfaceDeclaration,
  PropertySignature,
  Type,
  TypeAliasDeclaration,
} from 'ts-morph';
import { mkdirSync, writeFileSync, existsSync, readFileSync } from 'fs';
import * as path from 'path';
import { renderSwift } from './swift-generator';
import { renderKotlin } from './kotlin-generator';

export interface CodegenOptions {
  sourceFile: string;
  iosOutDir?: string;
  androidOutDir?: string;
  /** When true, returns the rendered strings without writing to disk. */
  dryRun?: boolean;
}

export interface CodegenResult {
  swift: Record<string, string>; // fileName → content
  kotlin: Record<string, string>;
  discovered: SchemaInterface[];
}

export interface SchemaField {
  name: string;
  typeExpr: SchemaTypeExpr;
  optional: boolean;
  docComment?: string;
}

export type SchemaTypeExpr =
  | { kind: 'primitive'; primitive: 'string' | 'number' | 'boolean' }
  | { kind: 'array'; inner: SchemaTypeExpr }
  | { kind: 'ref'; name: string }
  | { kind: 'literal'; value: string | number | boolean }
  | { kind: 'stringUnion'; values: string[] }
  | { kind: 'record'; valueType: SchemaTypeExpr }
  | { kind: 'nullable'; inner: SchemaTypeExpr }
  /** string | number | boolean union (JSON-compatible any value). */
  | { kind: 'jsonPrimitive' };

export interface SchemaInterface {
  name: string;
  fields: SchemaField[];
  docComment?: string;
}

export interface SchemaTypeAlias {
  name: string;
  values: string[];
  docComment?: string;
}

const HEADER = `// Auto-generated by @erne/monitor schema-codegen — do not edit by hand.
// Source: src/types/events.ts
`;

/** Reads interfaces from a TypeScript source file into a portable schema. */
export function parseSchemaFromFile(sourceFile: string): {
  interfaces: SchemaInterface[];
  aliases: SchemaTypeAlias[];
} {
  const project = new Project({
    compilerOptions: {
      strict: true,
      target: ts.ScriptTarget.ES2020,
      module: ts.ModuleKind.ESNext,
      moduleResolution: ts.ModuleResolutionKind.Bundler,
      skipLibCheck: true,
      noEmit: true,
    },
  });
  const src = project.addSourceFileAtPath(sourceFile);
  const interfaces: SchemaInterface[] = [];
  const aliases: SchemaTypeAlias[] = [];

  for (const decl of src.getInterfaces()) {
    if (!shouldInclude(decl)) continue;
    interfaces.push(buildInterface(decl));
  }

  for (const alias of src.getTypeAliases()) {
    const parsed = buildStringUnionAlias(alias);
    if (parsed) aliases.push(parsed);
  }

  interfaces.sort((a, b) => a.name.localeCompare(b.name));
  aliases.sort((a, b) => a.name.localeCompare(b.name));
  return { interfaces, aliases };
}

function shouldInclude(decl: InterfaceDeclaration): boolean {
  const name = decl.getName();
  if (!name) return false;
  // Auto-include anything ending in EventData / Payload / EventEnvelope
  // / EventContext / EventDevice / EventApp / EventSession / EventMemory.
  if (/(Payload|EventData|Envelope|Context|Device|App|Session|Memory)$/.test(name)) {
    return true;
  }
  const jsdoc = decl.getJsDocs().map((d) => d.getText()).join('\n');
  return /@codegen-include/.test(jsdoc);
}

function buildInterface(decl: InterfaceDeclaration): SchemaInterface {
  const name = decl.getName();
  const doc = decl.getJsDocs()[0]?.getCommentText() ?? undefined;
  const fields: SchemaField[] = [];
  for (const prop of decl.getProperties()) {
    fields.push(buildField(prop));
  }
  return {
    name,
    fields,
    ...(doc !== undefined ? { docComment: doc } : {}),
  };
}

function buildField(prop: PropertySignature): SchemaField {
  const name = prop.getName();
  const optional = prop.hasQuestionToken();
  const type = prop.getType();
  let typeExpr = buildType(type, prop.getTypeNode()?.getText() ?? '');
  // If the property has a question token the type already includes
  // undefined in its union. Avoid double-wrapping by unwrapping one
  // nullable layer when optional is true.
  if (optional && typeExpr.kind === 'nullable') {
    typeExpr = typeExpr.inner;
  }
  const doc = prop.getJsDocs()[0]?.getCommentText() ?? undefined;
  return {
    name,
    typeExpr,
    optional,
    ...(doc !== undefined ? { docComment: doc } : {}),
  };
}

function buildType(type: Type, textHint: string): SchemaTypeExpr {
  // ts-morph sometimes represents `boolean` as the `true | false` union.
  // Handle it BEFORE the generic union branch so we don't raise.
  if (type.isBoolean()) return { kind: 'primitive', primitive: 'boolean' };

  // Nullable union: X | null → nullable(X)
  if (type.isUnion()) {
    const parts = type.getUnionTypes();
    const nulls = parts.filter((p) => p.isNull() || p.isUndefined());
    const nonNull = parts.filter((p) => !p.isNull() && !p.isUndefined());
    if (nulls.length > 0 && nonNull.length === 1) {
      return { kind: 'nullable', inner: buildType(nonNull[0]!, textHint) };
    }
    // All members are string literals → stringUnion
    if (nonNull.length >= 2 && nonNull.every((p) => p.isStringLiteral())) {
      const values = nonNull
        .map((p) => p.getLiteralValue() as string)
        .sort();
      return { kind: 'stringUnion', values };
    }
    // Single literal
    if (nonNull.length === 1 && nonNull[0]!.isStringLiteral()) {
      return { kind: 'literal', value: nonNull[0]!.getLiteralValue() as string };
    }
    // string | number | boolean → JSON-compatible any value
    if (
      nonNull.length >= 2 &&
      nonNull.every(
        (p) =>
          p.isString() ||
          p.isStringLiteral() ||
          p.isNumber() ||
          p.isNumberLiteral() ||
          p.isBoolean() ||
          p.isBooleanLiteral(),
      )
    ) {
      const hasString = nonNull.some((p) => p.isString() || p.isStringLiteral());
      const hasNumber = nonNull.some((p) => p.isNumber() || p.isNumberLiteral());
      const hasBool = nonNull.some((p) => p.isBoolean() || p.isBooleanLiteral());
      if ((hasString && hasNumber) || (hasString && hasBool) || (hasNumber && hasBool)) {
        return { kind: 'jsonPrimitive' };
      }
    }
    throw new Error(
      `Unsupported union type "${textHint}" — only X | null, string literal unions, single literals, or string|number|boolean mixes are allowed.`,
    );
  }

  if (type.isString() || type.isStringLiteral()) {
    if (type.isStringLiteral()) {
      return { kind: 'literal', value: type.getLiteralValue() as string };
    }
    return { kind: 'primitive', primitive: 'string' };
  }
  if (type.isNumber()) return { kind: 'primitive', primitive: 'number' };
  if (type.isBoolean() || type.isBooleanLiteral()) {
    return { kind: 'primitive', primitive: 'boolean' };
  }
  if (type.isArray()) {
    const elem = type.getArrayElementType();
    if (!elem) throw new Error(`Array type "${textHint}" has no element type`);
    return { kind: 'array', inner: buildType(elem, textHint) };
  }

  // Record<string, X> — ts-morph represents this as an object type with
  // a string index signature.
  const indexInfo = type.getStringIndexType();
  if (indexInfo) {
    return { kind: 'record', valueType: buildType(indexInfo, textHint) };
  }

  // Named interface reference
  const symbol = type.getSymbol() ?? type.getAliasSymbol();
  if (symbol) {
    return { kind: 'ref', name: symbol.getName() };
  }

  throw new Error(
    `Unsupported type "${textHint}" — codegen cannot translate it. Rewrite using primitives, arrays, optionals, or nested interfaces.`,
  );
}

function buildStringUnionAlias(
  alias: TypeAliasDeclaration,
): SchemaTypeAlias | null {
  const name = alias.getName();
  if (!name) return null;
  const node = alias.getTypeNode();
  if (!node) return null;
  const type = alias.getType();
  if (!type.isUnion()) return null;
  const members = type.getUnionTypes();
  if (!members.every((m) => m.isStringLiteral())) return null;
  const values = members
    .map((m) => m.getLiteralValue() as string)
    .sort();
  const doc = alias.getJsDocs()[0]?.getCommentText() ?? undefined;
  return {
    name,
    values,
    ...(doc !== undefined ? { docComment: doc } : {}),
  };
}

/**
 * Builds the SchemaInterface list from a source file and hands it to
 * the Swift + Kotlin generators. Returns { swift, kotlin } — maps of
 * fileName → rendered content — and optionally writes them to disk.
 */
export async function generateSchemas(
  options: CodegenOptions,
): Promise<CodegenResult> {
  const { interfaces, aliases } = parseSchemaFromFile(options.sourceFile);

  const swiftFiles: Record<string, string> = {};
  const kotlinFiles: Record<string, string> = {};

  swiftFiles['ErneMonitorSchema.swift'] =
    HEADER + renderSwift(interfaces, aliases);
  kotlinFiles['ErneMonitorSchema.kt'] =
    HEADER + renderKotlin(interfaces, aliases);

  if (!options.dryRun) {
    if (options.iosOutDir) {
      mkdirSync(options.iosOutDir, { recursive: true });
      for (const [name, content] of Object.entries(swiftFiles)) {
        const outPath = path.join(options.iosOutDir, name);
        if (!existsSync(outPath) || readFileSync(outPath, 'utf8') !== content) {
          writeFileSync(outPath, content, 'utf8');
        }
      }
    }
    if (options.androidOutDir) {
      mkdirSync(options.androidOutDir, { recursive: true });
      for (const [name, content] of Object.entries(kotlinFiles)) {
        const outPath = path.join(options.androidOutDir, name);
        if (!existsSync(outPath) || readFileSync(outPath, 'utf8') !== content) {
          writeFileSync(outPath, content, 'utf8');
        }
      }
    }
  }

  return { swift: swiftFiles, kotlin: kotlinFiles, discovered: interfaces };
}
